// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Admin struct {
	ID     string
	IsCore bool
}

type Moder struct {
	ID string
}

type User struct {
	ID             string
	Name           string
	Email          string
	Password       string
	EmailConfirmed bool
}
