// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int32
	Name           string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
}
