// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
)

const get = `-- name: Get :one
SELECT id, name, email, hashed_password, created_at
FROM users
WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const save = `-- name: Save :one
INSERT INTO users(name, email, hashed_password, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id
`

type SaveParams struct {
	Name           string
	Email          string
	HashedPassword string
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) (int32, error) {
	row := q.db.QueryRow(ctx, save, arg.Name, arg.Email, arg.HashedPassword)
	var id int32
	err := row.Scan(&id)
	return id, err
}
